# Generated by Django 4.2.7 on 2024-02-20 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaveDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('sampling_rate', models.IntegerField()),
                ('main_data', models.JSONField()),
                ('exe_data', models.JSONField()),
                ('create', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('right_left_mix_hand', models.CharField(choices=[('left', 'چپ'), ('right', 'راست'), ('mix', 'چپ و راست')], max_length=10)),
                ('gender', models.IntegerField(choices=[(0, 'مرد'), (1, 'زن')])),
                ('phone', models.CharField(max_length=20)),
                ('national_code', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('signals', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='check_impedance.savedatamodel')),
            ],
        ),
    ]
